apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    component: mysql
    project: roboshop
    tier: database
type: Opaque #user-defined data so opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="